version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: datacenter_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_setup.sql:/docker-entrypoint-initdb.d/01-setup.sql:ro
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - datacenter_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 10
      interval: 30s

  # Datacenter Monitoring Application
  datacenter_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: datacenter_monitoring
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - DB_POOL_SIZE=${DB_POOL_SIZE}
      - DETECTION_MODEL_PATH=${DETECTION_MODEL_PATH}
      - PPE_DETECTION_MODEL_PATH=${PPE_DETECTION_MODEL_PATH}
      - POSE_ESTIMATION_MODEL_PATH=${POSE_ESTIMATION_MODEL_PATH}
      - POSE_ENABLED=${POSE_ENABLED}
      - NUMBER_OF_CAMERAS=${NUMBER_OF_CAMERAS}
      - BATCH_SIZE=${BATCH_SIZE}
      - READER_FPS_LIMIT=${READER_FPS_LIMIT}
      - PPE_DETECTION_ENABLED=${PPE_DETECTION_ENABLED}
      - TAILGATING_TIME_WINDOW=${TAILGATING_TIME_WINDOW}
      - LOITERING_THRESHOLD=${LOITERING_THRESHOLD}
      - TAMPER_DETECTION_ENABLED=${TAMPER_DETECTION_ENABLED}
      - SMS_ENABLED=${SMS_ENABLED}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - ALERT_PHONE_NUMBERS=${ALERT_PHONE_NUMBERS}
      - GCP_PROJECT=${GCP_PROJECT}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - LOG_LEVEL=${LOG_LEVEL}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
    volumes:
      # Models directory
      - ./models:/app/models:ro
      # Logs directory
      - ./logs:/app/logs
      # Frames storage
      - ./frames:/app/frames
      # Videos storage  
      - ./videos:/app/videos
      # Configuration files
      - ./configs:/app/configs:ro
      # GCP Service Account Key (if using GCP)
      - ./gcp-service-account.json:/app/gcp-key.json:ro
    ports:
      - "8000:8000"  # For future API/dashboard
    networks:
      - datacenter_network
    # GPU support (uncomment if using GPU)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Alternative for older docker-compose versions:
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      timeout: 30s
      retries: 3
      interval: 60s

  # Redis (Optional - for caching and session management)
  redis:
    image: redis:7-alpine
    container_name: datacenter_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - datacenter_network
    command: redis-server --appendonly yes

  # Nginx (Optional - for load balancing and reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: datacenter_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - datacenter_app
    networks:
      - datacenter_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  datacenter_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16